### PR TITLE
Show contribution new

### PR DESCRIPTION
**Pull request by uliska**
Now with an option `show_contribution` (default: `false` to keep existing projects) and unit test.

### CODE REVIEW

**Comment by uliska** [comment]
I'm not sure, but I think the failure is not related to the patch.

**Comment by timvink** [comment]
Great, thanks for the PR! 

Could you also update the `README.md` to inform users about the new functionality?  See https://github.com/timvink/mkdocs-git-revision-date-localized-plugin for example.

I will try to find some time this afternoon to see why codecov upload is failing, indeed doesn't seem related to the patch. And I will release new version to PyPi after this PR is merged.

**Comment by uliska** [comment]
Please do not release a new version yet. I still want to do the `aggregate_on` option, and that seems to be all I need from this plugin at this point.

**Comment by uliska** [comment]
I had forgotten to redo this from my original PR. It is annoying to read the `(100.00%)` for pages with a single author ...

**Comment by timvink** [comment]
One of the unit tests is still failing (`test_summarize_authors`), on the second `assert`. Can you have a look?

**Comment by uliska** [comment]
Sorry, I didn't updated the tests after the last commit which -- purposely -- changed the behaviour

**Comment by timvink** [comment]
I figured out why the build is failing on codecov upload:

> Secrets are not passed to workflows that are triggered by a pull request from a fork. 

There's one more design consideration we can make. Because of your elegant solution with the aggregation, we didn't need an option for that one. 

The contribution percentage is already available in `git_authors`, for advanced users looking to customize or create a theme. So the way I view it, adding the contribution percentage is a nice convenience for users.

Instead of hiding this functionality behind an option, we could also just expose a second markdown tag, so {{ git_authors_summary }} and {{ git_authors_contribution_summary }}. This has some benefits:

- Nothing to configure for users
- Short README
- Less code

What do you think?

**Comment by uliska** [comment]
> What do you think?

I haven't had sufficient experience with MkDocs plugins to have a fully informed opinion on this, so please take the following as sort-of-educated guesses:

> Nothing to configure for users

If I'm not mistaken we have two steps: theme customization and MkDocs configuration. If the theme supports the `git_authors_summary` template (either a customized theme or maybe one day third-party plugins like Material (I mean, it *does* already support the revision-date plugin, doesn't it?)) then a "normal" user can configure the appearance in the config file, which is much cleaner than messing with the theme templates. OTOH someone who configures their own theme files would probably not find it too much of a hassle to additionally add a config line.

> Short README

Sure? I don't think documenting an option is much more exp[a|e]nsive than documenting an additional theme template.

> Less code

It's only a guess, but I would estimate that there will be more configuration options in the future.

**Comment by timvink** [comment]
I'm not sure more configuration options will follow, but let's keep it as is for now.

**Pull request merged**
