### PR TITLE
Fix in-memory

### LINKED ISSUE #91: MkApi 3.x breaks this plugin
```
DEBUG   -  Running `files` event from plugin 'mkapi'
DEBUG   -  Running `files` event from plugin 'git-authors'
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/__main__.py", line 288, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 292, in build
    files = config.plugins.on_files(files, config=config)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/plugins.py", line 593, in on_files
    return self.run_event('files', files, config=config)
  File "/usr/local/lib/python3.10/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mkdocs_git_authors_plugin/plugin.py", line 124, in on_files
    if path.endswith(".md"):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
Haven't really checked anything in depth yet, but just updating mkapi from v2 to v3 causes the docs pipeline to fail here.
I assume it could be related to files [alternatively stored in memory](https://www.mkdocs.org/dev-guide/api/#mkdocs.structure.files.File)

### PR DESCRIPTION
**Pull request by twsl**
Fix #91

### CODE REVIEW

**Comment by twsl** [comment]
The tests are basically a mess due to how the dependencies are managed. Doesn't help, that `mkapi` does not expose a version property. If you have additional suggestions, let me know

**Comment by twsl** [comment]
@timvink can we get this merged?

**Comment by timvink** [comment]
Hee, thanks for fixing this!

There is one more thing we should check, there is an attribute for generated files that some plugins use:

https://github.com/mkdocs/mkdocs/pull/3344/files

**Comment by twsl** [comment]
what exactly do you want to check? or just include it to log which plugin might have been the culprit?

**Comment by timvink** [comment]
Your current way to check for generated files is by checking if src_path is None. But that's only true for generated files that are in Memory. Some generated files do have a src_path (written to disk), but no git info. 

So extend the check to look for the generated by attribute

**Comment by twsl** [comment]
I hope, this is what you meant. If not, maintainers are allowed to edit 😆

**Comment by timvink** [comment]
Thanks again for picking this up and fixing it! 🙏🏻

**Pull request merged**
